project_name: tvbit-bot
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd
    binary: tvbit-bot
    ldflags:
      - -s -w
      - -X github.com/rluisr/tvbit-bot/pkg/external.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto